function MARZA1128Aprobelayout = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  MARZA1128APROBELAYOUT = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  MARZA1128APROBELAYOUT = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  MARZA1128APROBELAYOUT = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MARZA1128Aprobelayout = importfile("/Users/Rishabh/Dropbox (MIT)/PUFFIN/Data/MARZ/bdot/MARZ_A1128A_probe_layout.xlsx", "Sheet1", [2, 16]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Apr-2022 11:47:28

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 16];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":I" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Probe", "CalFactorTsV", "Radiusmm", "Holder", "LOS", "BT", "Polarity", "VarName8", "SignalName"];
opts.VariableTypes = ["double", "double", "double", "categorical", "double", "categorical", "categorical", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["VarName8", "SignalName"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Holder", "BT", "Polarity", "VarName8", "SignalName"], "EmptyFieldRule", "auto");

% Import the data
MARZA1128Aprobelayout = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":I" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    MARZA1128Aprobelayout = [MARZA1128Aprobelayout; tb]; %#ok<AGROW>
end

end