function InductiveProbes = importMARZ4Data(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  INDUCTIVEPROBES = IMPORTFILE2(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  INDUCTIVEPROBES = IMPORTFILE2(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  InductiveProbes = importfile2("/Users/rishabhdatta/Dropbox (MIT)/PUFFIN group/Data/Z/MARZ/Shots/MARZ4_z3978/Inductive Probes/InductiveProbes.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Apr-2024 16:21:07

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TimensBADCV7", "AmplitudeBADCV7", "TimensBADCV8", "AmplitudeBADCV8", "TimensBADV5TBP", "AmplitudeBADV5TBP", "TimensBADV6TBP", "AmplitudeBADV6TBP", "TimensBADV7TBP", "AmplitudeBADV7TBP", "TimensBADVA10", "AmplitudeBADVA10", "TimensBADVA11", "AmplitudeBADVA11", "TimensBADVA12", "AmplitudeBADVA12", "TimensBADVA9", "AmplitudeBADVA9", "TimensBADVC5", "AmplitudeBADVC5", "TimensBADVC6", "AmplitudeBADVC6"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
InductiveProbes = readtable(filename, opts);

end