function MARZprobecalsNov2022S2 = importfileMarz2(workbookFile, sheetName, dataLines)
%IMPORTFILE2 Import data from a spreadsheet
%  MARZPROBECALSNOV2022S2 = IMPORTFILE2(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  MARZPROBECALSNOV2022S2 = IMPORTFILE2(FILE, SHEET) reads from the
%  specified worksheet.
%
%  MARZPROBECALSNOV2022S2 = IMPORTFILE2(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MARZprobecalsNov2022S2 = importfile2("/Users/rishabhdatta/Dropbox (MIT)/PUFFIN/Data/MARZ/bdot/20221207_MARZ_probe_cals_Nov2022.xlsx", "Dec_Shot1", [2, 15]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Dec-2022 17:34:10

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 15];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":K" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Probe", "CalFactor", "Holder", "LOS", "Label", "SignalName", "BT", "Polarity", "Radius", "SignalNameincorrect", "DASChannel"];
opts.VariableTypes = ["string", "double", "categorical", "string", "double", "string", "categorical", "categorical", "double", "string", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Probe", "LOS", "SignalName", "SignalNameincorrect"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Probe", "Holder", "LOS", "SignalName", "BT", "Polarity", "SignalNameincorrect"], "EmptyFieldRule", "auto");

% Import the data
MARZprobecalsNov2022S2 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":K" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    MARZprobecalsNov2022S2 = [MARZprobecalsNov2022S2; tb]; %#ok<AGROW>
end

end