function InductiveProbeLabelsMARZcopy = importfileMARZ4(workbookFile, sheetName, dataLines)
%IMPORTFILE2 Import data from a spreadsheet
%  INDUCTIVEPROBELABELSMARZCOPY = IMPORTFILE2(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  INDUCTIVEPROBELABELSMARZCOPY = IMPORTFILE2(FILE, SHEET) reads from
%  the specified worksheet.
%
%  INDUCTIVEPROBELABELSMARZCOPY = IMPORTFILE2(FILE, SHEET, DATALINES)
%  reads from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  InductiveProbeLabelsMARZcopy = importfile2("/Users/rishabhdatta/Dropbox (MIT)/PUFFIN group/Data/Z/MARZ/Shots/MARZ4_z3978/Inductive Probes/InductiveProbeLabelsMARZ copy.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Apr-2024 16:14:52

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Label", "Probe", "CalFactor", "SignalName", "Radius","Polarity"];
opts.VariableTypes = ["double", "string", "double", "string", "double","string"];

% Specify variable properties
opts = setvaropts(opts, ["Probe", "SignalName"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Probe", "SignalName"], "EmptyFieldRule", "auto");

% Import the data
InductiveProbeLabelsMARZcopy = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    InductiveProbeLabelsMARZcopy = [InductiveProbeLabelsMARZcopy; tb]; %#ok<AGROW>
end

end